name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  testing-and-deployment:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install uv
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      # Cache uv dependencies
      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      # Sync dependencies
      - name: Install dependencies
        run: |
          uv sync --frozen

      # Run DVC pipeline inside uv env
      - name: Run pipeline
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          uv run dvc repro

      # Run tests
      # - name: Run model tests
      #   env:
      #     DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      #   run: |
      #     uv run python -m unittest tests/test_model.py

      # Promote model
      # - name: Promote model
      #   if: success()
      #   env:
      #     DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      #   run: |
      #     uv run python scripts/promote_model.py
